### ISSUE TITLE
AFK Detection

### ISSUE THREAD

**Issue by DashCee** [1pulse/factorio_biter_battles#25]
AFK detection should be added, to stop team imbalance.
This should only  apply to the players that not spectating, as some people just like to spectate to socialise, as well as it being useful to see the server if people AFK in spectator mode

**Comment by guymaor86** [comment]
don't think this is really needed
if one of the admins does: `/config`
then the following screen will pop up and we can set AFK auto-kick
![image](https://user-images.githubusercontent.com/8980910/102050862-cd199680-3da0-11eb-8804-d38cfb17554a.png)

**Comment by 1pulse** [comment]
Ok it will be enabled in next game restart / map upload, on in next days probably

**Comment by 1pulse** [comment]
ok done with 30 min
